version: '3.7'
services:
  # https://github.com/jesec/rtorrent
  # https://github.com/jesec/flood
  rtorrent:
    image: jesec/rtorrent-flood:latest
    container_name: jesec-rtorrent-flood
    network_mode: host
    restart: unless-stopped
    user: ${UID:-1026}:${GID:-100}
    environment:
      HOME: /config
    command:
      - --auth=none
      - --host=${HOST:-0.0.0.0}
      - --port=${PORT:-3001}
      - --allowedpath=/data/
      - --rundir=/config/flood
      - --rtsocket=/config/rtorrent/rpc.sock
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: /volume1/downloads/apps
        target: /data/apps
      - type: bind
        source: /volume1/video/movies
        target: /data/movies
      - type: bind
        source: /volume1/downloads/music
        target: /data/music
      - type: bind
        source: /volume1/video/series
        target: /data/series
