#!/usr/bin/env bash
set -Eeuo pipefail
exec docker run \
    --rm \
    --tmpfs '/tmp:rw,noexec,nosuid,size=1g' \
    --volume '/volume1/music/R/Rádio Etiópia:/out' \
    --user Richard:users \
    radio-etiopia-task
