version: '3.7'
services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2021.12.4
    network_mode: host
    restart: unless-stopped
    command: proxy-dns --address 0.0.0.0 --port 5553
    user: nobody
    working_dir: /tmp
