#!/usr/bin/env bash
set -Eeuo pipefail

# The following redirects any incoming UDP :53 requests to :5553. This is
# required because our NAS does not have `setcap` nor `authbind` and our
# container is thus unable to bind to :53. We can fix this with the following
# `iptables` rules.
#
# - https://unix.stackexchange.com/questions/334098

if ((EUID != 0)); then
    echo 'Super-user privileges are required to change iptables.' >&2
    exit 1
fi

readonly interface=${1:-bond0}

main() {
    iptables -A INPUT -p udp --dport 53 -j ACCEPT
    iptables -A INPUT -p udp --dport 5553 -j ACCEPT

    # This is for incoming requests from other computers.
    iptables -A PREROUTING -t nat -i "$interface" -p udp --dport 53 -j REDIRECT --to-port 5553

    # This is for local requests from the current computer so that we can use
    # our DoH server for the NAS itself as well.
    iptables -A OUTPUT -t nat -p udp --dport 53 -j REDIRECT --to-port 5553
}

if ! main; then
    echo 'Have a look at https://unix.stackexchange.com/questions/335214 in case this operation failed due to a missing nat table.' >&2
    exit 1
fi
